 services:
  mongodb:
    env_file: ".env"
    image: mongo:8.0
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  pipeline:
    env_file: ".env"
    environment:
      - MONGODB_HOST=mongodb
    build:
      context: .
    volumes:
      - ./dataset:/data-engineering-lab-hw3/dataset:ro
      - ./reporter:/data-engineering-lab-hw3/reporter
    command: bash -c "poetry run python -m src.hw3.run"
    depends_on:
      mongodb:
        condition: service_healthy
