import os

CASSANDRA_HOST = os.environ.get("CASSANDRA_HOST", "127.0.0.1")
CASSANDRA_USER = os.environ.get("CASSANDRA_USER")
CASSANDRA_PASSWORD = os.environ.get("CASSANDRA_PASSWORD")

CASSANDRA_KEYSPACE = "ad_events"

CASSANDRA_CONCURRENT_REQUESTS = 64
MAX_BATCH_SIZE = CASSANDRA_CONCURRENT_REQUESTS * 20

MONTH_BUCKET_FORMAT = "%Y-%m"
