import os

DATASET_PATH = "./dataset/amazon_reviews.csv"
DATABASE_NAME = "reviews"

MONGODB_USERNAME = os.environ.get("MONGO_INITDB_ROOT_USERNAME")
MONGODB_PASSWORD = os.environ.get("MONGO_INITDB_ROOT_PASSWORD")
MONGODB_HOST = os.environ.get("MONGODB_HOST")

MONGODB_URI = f"mongodb://{MONGODB_USERNAME}:{MONGODB_PASSWORD}@{MONGODB_HOST}:27017/?authSource=admin"

SPARK_MASTER_HOST = os.environ.get("SPARK_MASTER_HOST", "192.168.0.241")
SPARK_MASTER_PORT = os.environ.get("SPARK_MASTER_PORT", "7077")

SPARK_MASTER_URL = f"spark://{SPARK_MASTER_HOST}:{SPARK_MASTER_PORT}"
SPARK_MONGO_CONNECTOR = os.environ.get("SPARK_MONGO_CONNECTOR")
